// Mock data for portfolio - Replace with Supabase data later

export const profileData = {
    name: "LongZu",
    title: "Full Stack Developer & Designer",
    bio: "Chào các bạn! Ở đây mình sẽ chia sẻ cho các bạn kinh nghiệm học IT, bí kíp được điểm cao, một số tool hữu ích và project cá nhân để các bạn tham khảo. Đặc biệt cho sinh viên UIT!",
    avatar: "/avatar.jpg",
    location: "Vietnam",
    email: "contact@longzu.dev",
    social: {
        github: "https://github.com/longzu",
        linkedin: "https://linkedin.com/in/longzu",
        facebook: "https://facebook.com/longzu",
    },
};

export const skills = [
    { name: "React / Next.js", icon: "⚛️", level: "expert" as const, category: "Frontend" },
    { name: "TypeScript", icon: "📘", level: "advanced" as const, category: "Language" },
    { name: "Node.js", icon: "🟢", level: "advanced" as const, category: "Backend" },
    { name: "Python", icon: "🐍", level: "intermediate" as const, category: "Language" },
    { name: "PostgreSQL", icon: "🐘", level: "advanced" as const, category: "Database" },
    { name: "TailwindCSS", icon: "🎨", level: "expert" as const, category: "Styling" },
    { name: "Docker", icon: "🐳", level: "intermediate" as const, category: "DevOps" },
    { name: "Git", icon: "📦", level: "advanced" as const, category: "Tools" },
    { name: "Figma", icon: "🎯", level: "intermediate" as const, category: "Design" },
    { name: "AWS", icon: "☁️", level: "intermediate" as const, category: "Cloud" },
];

export const timeline = [
    {
        year: "2024",
        title: "Senior Developer",
        description: "Leading development of enterprise applications and mentoring junior developers.",
        organization: "Tech Company",
        type: "work" as const,
    },
    {
        year: "2023",
        title: "Freelance Developer",
        description: "Started freelancing, building custom web solutions for various clients.",
        type: "work" as const,
    },
    {
        year: "2022",
        title: "Bachelor's Degree in Computer Science",
        description: "Graduated with honors, specialized in Software Engineering.",
        organization: "University of Technology",
        type: "education" as const,
    },
    {
        year: "2021",
        title: "First Place - Hackathon",
        description: "Won first place in national coding competition with innovative project.",
        type: "achievement" as const,
    },
    {
        year: "2020",
        title: "Junior Developer",
        description: "Started career as a junior developer, learning enterprise development practices.",
        organization: "Startup Inc.",
        type: "work" as const,
    },
];

export const projects = [
    {
        id: 1,
        title: "E-Commerce Platform",
        slug: "ecommerce-platform",
        description: "A full-featured e-commerce platform with payment integration, inventory management, and admin dashboard.",
        image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80",
        tags: ["Next.js", "Stripe", "PostgreSQL", "TailwindCSS"],
        demoUrl: "https://demo.example.com",
        sourceUrl: "https://github.com/longzu/ecommerce",
        isPaid: false,
        category: "Web App",
    },
    {
        id: 2,
        title: "DKHP Tool",
        slug: "dkhp-tool",
        description: "Automated course registration tool for university students with smart scheduling.",
        image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&q=80",
        tags: ["Python", "Selenium", "React", "API"],
        isPaid: true,
        category: "Tool",
    },
    {
        id: 3,
        title: "Portfolio Template",
        slug: "portfolio-template",
        description: "Modern, responsive portfolio template for developers and designers.",
        image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80",
        tags: ["Next.js", "TailwindCSS", "Framer Motion"],
        demoUrl: "https://template.example.com",
        sourceUrl: "https://github.com/longzu/portfolio-template",
        isPaid: false,
        category: "Template",
    },
    {
        id: 4,
        title: "Task Management App",
        slug: "task-management",
        description: "Collaborative task management with real-time updates and team features.",
        image: "https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=800&q=80",
        tags: ["React", "Node.js", "Socket.io", "MongoDB"],
        demoUrl: "https://tasks.example.com",
        isPaid: false,
        category: "Web App",
    },
    {
        id: 5,
        title: "AI Content Generator",
        slug: "ai-content-generator",
        description: "AI-powered content generation tool for marketing and social media.",
        image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&q=80",
        tags: ["Python", "OpenAI", "FastAPI", "React"],
        isPaid: true,
        category: "AI Tool",
    },
    {
        id: 6,
        title: "Weather Dashboard",
        slug: "weather-dashboard",
        description: "Beautiful weather dashboard with forecasts and location-based data.",
        image: "https://images.unsplash.com/photo-1504608524841-42fe6f032b4b?w=800&q=80",
        tags: ["React", "API", "Charts", "Geolocation"],
        demoUrl: "https://weather.example.com",
        sourceUrl: "https://github.com/longzu/weather",
        isPaid: false,
        category: "Mini App",
    },
];

export const blogPosts = [
    {
        id: 1,
        title: "Building Scalable React Applications",
        slug: "building-scalable-react-apps",
        excerpt: "Learn the best practices for structuring and scaling your React applications for enterprise use.",
        content: "",
        date: "Jan 20, 2024",
        readTime: "8 min read",
        tags: ["React", "Architecture", "Best Practices"],
        featured: true,
    },
    {
        id: 2,
        title: "Getting Started with Next.js 14",
        slug: "nextjs-14-guide",
        excerpt: "A comprehensive guide to the new features in Next.js 14 and how to migrate your existing projects.",
        content: "",
        date: "Jan 15, 2024",
        readTime: "10 min read",
        tags: ["Next.js", "Tutorial", "JavaScript"],
        featured: false,
    },
    {
        id: 3,
        title: "Mastering TailwindCSS",
        slug: "mastering-tailwindcss",
        excerpt: "Tips and tricks to become more productive with TailwindCSS in your projects.",
        content: "",
        date: "Jan 10, 2024",
        readTime: "6 min read",
        tags: ["CSS", "TailwindCSS", "Design"],
        featured: false,
    },
    {
        id: 4,
        title: "Database Design Best Practices",
        slug: "database-design-best-practices",
        excerpt: "Essential principles for designing efficient and scalable database schemas.",
        content: "",
        date: "Jan 5, 2024",
        readTime: "12 min read",
        tags: ["Database", "PostgreSQL", "Architecture"],
        featured: false,
    },
];

export const services = [
    {
        id: 1,
        title: "Landing Page",
        description: "Perfect for showcasing your product or service with a stunning single-page website.",
        price: "3.000.000đ",
        priceNote: "/ project",
        features: [
            "Responsive design",
            "SEO optimized",
            "Contact form integration",
            "1 round of revisions",
            "Delivery in 5-7 days",
        ],
        highlighted: false,
    },
    {
        id: 2,
        title: "Business Website",
        description: "Complete multi-page website for your business with all essential features.",
        price: "8.000.000đ",
        priceNote: "/ project",
        features: [
            "Up to 5 pages",
            "Responsive design",
            "SEO optimized",
            "CMS integration",
            "Contact & booking forms",
            "2 rounds of revisions",
            "Delivery in 2 weeks",
        ],
        highlighted: true,
    },
    {
        id: 3,
        title: "Custom Web App",
        description: "Full-featured web application tailored to your specific needs.",
        price: "15.000.000đ",
        priceNote: "+ (tùy yêu cầu)",
        features: [
            "Custom features",
            "Database design",
            "User authentication",
            "Admin dashboard",
            "API development",
            "Ongoing support",
            "Timeline based on scope",
        ],
        highlighted: false,
    },
];

export const cvData = {
    pdfUrl: "/cv.pdf",
    templates: [
        { id: 1, name: "Modern Dark", preview: "/templates/modern-dark.png" },
        { id: 2, name: "Clean Light", preview: "/templates/clean-light.png" },
        { id: 3, name: "Creative", preview: "/templates/creative.png" },
    ],
};
